feat: Add metadata filter on transactions list
numary/ledger pull request #259
Opened 2022-06-30 20:25 UTC by gfyrag

# 'metadata' filter on transactions list

This add the metadata filter on transactions list as the accounts endpoint.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Technical debt

## What parts of the code are impacted ?
* pkg/storage
* pkg/api

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-07-01 13:36 UTC, altitude submitted a review, later dismissed

2022-07-01 13:36 UTC, altitude commented on pkg/storage/sqlstorage/store_test.go
> +		assert.Equal(t, 1, cursor.PageSize)
to be updated after merge of #260 :)

2022-07-01 17:04 UTC, gfyrag commented on pkg/storage/sqlstorage/store_test.go
> +		assert.Equal(t, 1, cursor.PageSize)
Yes. After merge #260 and rebase this PR, the test will not pass.
But #260 is not fully approve :(

2022-07-04 15:54 UTC, jdupas22 submitted a review, later dismissed

2022-07-05 14:15 UTC, antoinegelloz requested changes

2022-07-05 14:15 UTC, antoinegelloz commented on pkg/storage/sqlstorage/transactions.go
> +	if len(metadata) > 0 {
This if could be removed :)

2022-07-06 08:53 UTC, jdupas22 submitted a review, later dismissed

2022-07-06 16:32 UTC, antoinegelloz approved these changes

2022-07-07 09:02 UTC, antoinegelloz submitted a review, later dismissed

2022-07-07 09:14 UTC, antoinegelloz approved these changes

2022-07-07 09:17 UTC, flemzord approved these changes

2022-07-07 09:17 UTC, merged