feat: Add doc to add a sdk
numary/ledger pull request #290
Opened 2022-07-19 15:25 UTC by gfyrag

# Add doc to create a SDK

Add a documentation to add a new SDK (see ./SDK.md).
Also add a specific PR template.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Technical debt

## What parts of the code are impacted ?
__Please describe the impacted parts of the code.__

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-21 07:37 UTC, flemzord submitted a review, later dismissed

2022-07-21 08:35 UTC, jdupas22 commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
i think we should rephrase this, seems unclear to me

2022-07-21 11:31 UTC, gfyrag commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
Ok. What point is not clear for you?

2022-07-21 16:43 UTC, antoinegelloz requested changes

2022-07-21 16:43 UTC, antoinegelloz commented on .github/PULL_REQUEST_TEMPLATE/pull_request_sdk_template.md
> +__Please be the more exhaustive you can__
```suggestion
__Please be as exhaustive as possible__
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +This doc refers to the tools named [task](https://taskfile.dev/)
```suggestion
This doc refers to the tool named [task](https://taskfile.dev/)
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +If you want to add a new languages, you have to configure some things.
```suggestion
If you want to add a new language, you have to configure a few things.
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +The config file must be added inside the directory sdk/configs/.
```suggestion
This file must be added inside the sdk/configs directory.
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +The filename MUST match the name of the involved api generator (ie java.yaml for java or php.yaml for php).
```suggestion
The file name MUST match the name of the involved api generator (i.e. java.yaml for java or php.yaml for php).
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
I don't understand this sentence neither 😢

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +You have to keep in mind the SDK will be hosted on github.com/numary/numary-sdk-<generator name> and so, you could have to define some properties for a language which would not exists on another lang
```suggestion
You have to keep in mind that the SDK will be hosted on github.com/numary/numary-sdk-<generator name>, so you could have to define some properties for a language which would not exist on another language.
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +Customization of the generated SDK can be achieved modifying the openapi generator builtins templates.
```suggestion
Customization of the generated SDK can be achieved by modifying the openapi generator builtins templates.
```

2022-07-21 16:43 UTC, antoinegelloz commented on SDK.md
> +You can modify them as well as you want.
```suggestion
You can edit them as much as you want.
```

2022-07-21 18:50 UTC, gfyrag commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
Some generator (java for example) provide configuration options to define the licence name. But it is not the case for all.
I want to express the fact, that if a generator provide those configuration options, we have to use them.

2022-07-22 07:41 UTC, jdupas22 commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
I still don't see it, why would the licence be set to MIT if the generator provide licence configuration ?

2022-07-26 19:30 UTC, gfyrag commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
It is just a best effort to set a licence on the generated sdk.

2022-07-26 19:30 UTC, gfyrag commented on SDK.md
> +If the generator provide required properties, you MUST define the licence to MIT.
(MIT was decided with @altitude and @flemzord )

2022-07-28 07:39 UTC, flemzord approved these changes

2022-08-01 13:52 UTC, merged