feat: Use appropriate type for 'timestamp' column in database
numary/ledger pull request #296
Opened 2022-07-21 13:40 UTC by gfyrag

# Use appropriate columns type for 'timestamp' field (transactions)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Technical debt

2022-08-05 08:52 UTC, jdupas22 submitted a review, later dismissed

2022-08-30 16:06 UTC, antoinegelloz requested changes

2022-08-30 16:06 UTC, antoinegelloz commented on pkg/storage/sqlstorage/migrates/12-update-timestamp-column-type/any_test.go
> +package _2_update_timestamp_column_type
```suggestion
package 12_update_timestamp_column_type
```

2022-08-30 16:06 UTC, antoinegelloz commented on pkg/storage/sqlstorage/migrates/12-update-timestamp-column-type/any_test.go
> +func TestMigrate11(t *testing.T) {
```suggestion
func TestMigrate12(t *testing.T) {
```

2022-08-31 07:20 UTC, antoinegelloz approved these changes

2022-08-31 12:01 UTC, jdupas22 approved these changes

2022-09-01 14:03 UTC, antoinegelloz approved these changes

2022-09-01 20:57 UTC, merged