Introduce new monetary int
numary/ledger pull request #310
Opened 2022-08-05 22:31 UTC by altitude

2022-08-19 15:04 UTC, antoinegelloz requested changes
Looks good to me!
Just think about removing the testlog.txt file :)

2022-08-19 15:04 UTC, antoinegelloz commented on Taskfile.yaml
> -        go test {{.TAGS}} -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile coverage.out -covermode atomic
I like to have the verbose mode in local testing, why do you want to remove it?
If you don't want logs, I prefer that you remove the verbose mode in the `tests` rule above, or create a `VERBOSE: "-v"` variable that can be overridden with `tasks VERBOSE=""` :)

2022-08-19 15:04 UTC, antoinegelloz commented on cmd/script_exec.go
> +					p.Amount.String(),
No need to call the `.String()` method, fmt will call it automatically thanks to the fmt.Stringer interface :)

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/core/monetary.go
> +func (a *MonetaryInt) Ltz() bool {
```suggestion
func (a *MonetaryInt) IsNeg() bool {
```
Wouldn't be more clear?

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/core/monetary.go
> +
useless line break

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/ledger/executor_test.go
>  		"wrong %v balance for account %v, expected: %d got: %d",
```suggestion
		"wrong %v balance for account %v, expected: %s got: %s",
```

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/ledger/process_test.go
> +				// a, _ := json.Marshal(res.GeneratedTransactions)
```suggestion
```
Oopsy ;)

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/ledger/volume_agg.go
> +	// }
```suggestion
```

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/storage/sqlstorage/migrates/9-add-pre-post-volumes/any_test.go
> +				// },
```suggestion
```

2022-08-19 15:04 UTC, antoinegelloz commented on pkg/storage/sqlstorage/migrates/9-add-pre-post-volumes/any_test.go
> +				// },
```suggestion
```

2022-08-29 11:48 UTC, flemzord submitted a review, later dismissed

2022-08-29 12:53 UTC, gfyrag commented on Taskfile.yaml
> -        go test {{.TAGS}} -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile coverage.out -covermode atomic
Pretty agree with @altitude the verbose logs complicate things most of the time.

2022-08-29 12:54 UTC, gfyrag commented on pkg/ledger/executor_test.go
>  		"wrong %v balance for account %v, expected: %d got: %d",
@antoinegelloz Why this modification?

2022-08-30 15:44 UTC, gfyrag approved these changes

2022-08-30 21:40 UTC, gfyrag commented on pkg/core/monetary.go
> +func (a *MonetaryInt) Ltz() bool {
Ltz is a common term. I think it is not a problem.

2022-08-31 07:16 UTC, antoinegelloz commented on Taskfile.yaml
> -        go test {{.TAGS}} -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile coverage.out -covermode atomic
Ok then, can we change the committed version to `Taskfile.dist.yml`, so I can override it with my own locally?
https://taskfile.dev/usage/#supported-file-names

2022-08-31 07:16 UTC, antoinegelloz commented on pkg/core/monetary.go
> +func (a *MonetaryInt) Ltz() bool {
Ok!

2022-08-31 08:55 UTC, gfyrag commented on Taskfile.yaml
> -        go test {{.TAGS}} -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile coverage.out -covermode atomic
Add variable VERBOSE to the Taskfile.
Give : 
```task tests VERBOSE=1```

2022-08-31 10:03 UTC, gfyrag submitted a review, later dismissed

2022-08-31 10:33 UTC, antoinegelloz submitted a review, later dismissed

2022-08-31 13:32 UTC, jdupas22 submitted a review, later dismissed

2022-08-31 14:35 UTC, antoinegelloz approved these changes

2022-08-31 14:35 UTC, jdupas22 approved these changes

2022-08-31 16:39 UTC, merged